from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import PlainTextResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from database import get_db, Assessment, ReadinessScore, AnalysisResult, User
from routers.auth import get_current_user
from services.ollama_service import OllamaService
import os

router = APIRouter()
ollama = OllamaService()

def load_prompt(filename: str) -> str:
    prompt_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "prompts", filename)
    try:
        with open(prompt_path, "r") as f:
            return f.read()
    except:
        return ""

@router.get("/{assessment_id}/markdown", response_class=PlainTextResponse)
async def export_report_markdown(
    assessment_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    result = await db.execute(select(Assessment).where(Assessment.id == assessment_id, Assessment.user_id == current_user.id))
    assessment = result.scalar_one_or_none()
    if not assessment:
        raise HTTPException(status_code=404, detail="Assessment not found")

    score_result = await db.execute(select(ReadinessScore).where(ReadinessScore.assessment_id == assessment_id))
    readiness = score_result.scalar_one_or_none()

    ar_result = await db.execute(select(AnalysisResult).where(AnalysisResult.assessment_id == assessment_id))
    analysis = ar_result.scalar_one_or_none()

    if not readiness or not analysis:
        raise HTTPException(status_code=400, detail="Analysis not complete. Please run analysis first.")

    exec_prompt = load_prompt("executive_report_generator.txt")
    summary_data = f"""
Organization: {assessment.organization}
Assessment: {assessment.name}
Overall Readiness Score: {readiness.overall_score}/100

Category Scores:
{chr(10).join([f"- {cat}: {data['score']}/100 - {data.get('justification','')}" for cat, data in readiness.category_scores.items()])}

Migration Risks Summary:
{str(analysis.result_data.get('migration_risks', ''))[:3000]}

Security Baseline:
{str(analysis.result_data.get('security_baseline', ''))[:2000]}

Compliance Gaps:
{str(analysis.result_data.get('compliance_gaps', ''))[:2000]}

Landing Zone Recommendations:
{str(analysis.result_data.get('landing_zone', ''))[:2000]}
"""
    exec_summary = await ollama.generate(f"{exec_prompt}\n\n{summary_data}")

    category_scores_md = "\n".join([
        f"| {cat} | {data['score']}/100 | {data.get('justification', '')[:100]} |"
        for cat, data in readiness.category_scores.items()
    ])

    report = f"""# Cloud Migration Readiness Report
**Organization:** {assessment.organization}
**Assessment:** {assessment.name}
**Date:** {str(assessment.created_at)[:10]}
**Overall Readiness Score:** {readiness.overall_score}/100

---

## Executive Summary

{exec_summary}

---

## Readiness Scores by Category

| Category | Score | Notes |
|----------|-------|-------|
{category_scores_md}

---

## Migration Risks

{analysis.result_data.get('migration_risks', 'No data available')}

---

## Security Baseline Assessment

{analysis.result_data.get('security_baseline', 'No data available')}

---

## Compliance Gap Analysis

{analysis.result_data.get('compliance_gaps', 'No data available')}

---

## Landing Zone Recommendations

{analysis.result_data.get('landing_zone', 'No data available')}

---

*Report generated by CloudShift AI — Powered by Ollama (Local AI)*
"""
    return PlainTextResponse(content=report, media_type="text/markdown")

@router.get("/{assessment_id}/summary")
async def get_report_summary(
    assessment_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    result = await db.execute(select(Assessment).where(Assessment.id == assessment_id, Assessment.user_id == current_user.id))
    assessment = result.scalar_one_or_none()
    if not assessment:
        raise HTTPException(status_code=404, detail="Assessment not found")

    score_result = await db.execute(select(ReadinessScore).where(ReadinessScore.assessment_id == assessment_id))
    readiness = score_result.scalar_one_or_none()

    ar_result = await db.execute(select(AnalysisResult).where(AnalysisResult.assessment_id == assessment_id))
    analysis = ar_result.scalar_one_or_none()

    return {
        "assessment": {"id": assessment.id, "name": assessment.name, "organization": assessment.organization},
        "readiness_score": readiness.overall_score if readiness else None,
        "category_scores": readiness.category_scores if readiness else None,
        "migration_risks": analysis.result_data.get("migration_risks") if analysis else None,
        "security_baseline": analysis.result_data.get("security_baseline") if analysis else None,
        "compliance_gaps": analysis.result_data.get("compliance_gaps") if analysis else None,
        "landing_zone": analysis.result_data.get("landing_zone") if analysis else None
    }
